#ifndef TIPO_H
#define TIPO_H

enum Tipo {
        ENTERO,
        DECIMAL,
        BOOLEANO,
        CARACTER,
        CADENA,
        ID,
        PARA,
        PARC,
        LLA,
        LLC,
        CORA,
        CORC,
        PNTCOMA,
        TIPO,
        ARREGLO,
        IGUAL,
        COMA,
        MAS,
        MENOS,
        POR,
        BARRA,
        IGUALQUE,
        DIFERENTEQUE,
        MENORQUE,
        MAYORQUE,
        MENORIGUALQUE,
        MAYORIGUALQUE,
        NOT,
        POT,
        AND,
        OR,
        DECREMENTO,
        INCREMENTO,
        IMPRIMIR,
        SHOW,
        SI,
        SINO,
        CICLO_PARA,
        CICLO_REPETIR,
    INICIO,
    BLOQUE,
    INSTRUCCION,
    DECLARACION,
    LISTA_ID,
    ASIGNACION,
    DIMENSIONES,
    ARREGLO_LISTA_EXPRESIONES,
    LISTA_EXPRESIONES,
    EXPRESION,
    PRINT,
    MESSAGE,
    IF,
    ELSEIF,
    ELSE,
    FOR,
    REPETIR
 };

#endif // TIPO_H
